language: erlang
notifications:
  email:
    - odo@mac.com
otp_release:
  - 17.3
  - 17.0
  - R16B03-1
  - R16B
  - R15B03
before_script: "./rebar get-deps compile"
script: "./rebar eunit skip_deps=true"
